In [49]:
import numpy as np
import torch as torch
from keras.datasets import fashion_mnist
import torch
(xtrain, ytrain), (xtest, ytest) = fashion_mnist.load_data()
xtrain = xtrain.reshape(60000, 784)
ytrain, ytest = ytrain.copy(), ytest.copy()
ytrain[ytrain != 8] = 0
ytrain[ytrain == 8] = 1
ytest[ytest != 8] = 0
ytest[ytest == 8] = 1

In [16]:
a = torch.tensor(2., requires_grad = True)
b = torch.tensor(3.)
c = a*b
c.backward()

In [17]:
a.grad

tensor(3.)

In [31]:
a = torch.ones(10, requires_grad = True)
sig = torch.nn.Sigmoid()
b = sig(a).sum()


In [33]:
a.grad

tensor([0.1966, 0.1966, 0.1966, 0.1966, 0.1966, 0.1966, 0.1966, 0.1966, 0.1966,
        0.1966])

In [32]:
b.backward()

In [ ]:
class FeedForward(torch.nn.Module):
    def __init__(self, input_size, hidden_size):
        super(Feedforward, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.fc1 = torch.nn.Linear(self.input_size, self.hidden_size)
        self.relu = torch.nn.ReLU()
        

In [100]:
xtensor = torch.transpose(torch.from_numpy(xtrain), 0, 1).float()
ytensor = torch.from_numpy(ytrain).float()

In [153]:
# W = 0.01 * torch.rand((1, 784), requires_grad = True) - 0.005
W = torch.tensor(initval, requires_grad = True)
H = torch.mv(W, xtensor[:,0])
sig = torch.nn.Sigmoid()
output = sig(H)
loss = ytensor[0] * torch.log(output) + (1 - ytensor[0]) * torch.log(output)


<ipython-input-153-f27f8c0c0213>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  W = torch.tensor(initval, requires_grad = True)


In [154]:
loss.backward()

In [156]:
W.grad

tensor([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           1.,   0.,   0.,  13.,  73.,   0.,   0.,   1.,   4.,   0.,   0.,   0.,
           0.,   1.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   3.,   0.,  36., 136., 127.,  62.,  54.,   0.,
           0.,   0.,   1.,   3.,   4.,   0.,   0.,   3.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,  

In [137]:
initval = torch.from_numpy(np.random.normal(0, 0.01, (1, 784))).float()

In [138]:
W = torch.tensor(initval, requires_grad = True)

<ipython-input-138-b50b072300e8>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  W = torch.tensor(initval, requires_grad = True)


In [272]:
initval = torch.from_numpy(np.random.normal(0, 0.01, (1, 784))).float()
W = torch.zeros((1, 784), requires_grad = True)
W = torch.nn.init.xavier_uniform_(W, gain = 0.0011)
for j in range(10):
    for i in range(10000):
        H = torch.mv(W, xtensor[:,i])
        sig = torch.nn.Sigmoid()
        output = sig(H)
        loss = -ytensor[i] * torch.log(output) - (1 - ytensor[i]) * torch.log(output)
        loss.backward()
#         losses.append()
        with torch.no_grad():
            W -= 0.000001 * W.grad
            W.grad.zero_()

In [273]:
for i in range(50):
    H = torch.mv(W, xtensor[:,i])
    sig = torch.nn.Sigmoid()
    output = sig(H)
    loss = -ytensor[i] * torch.log(output) - (1 - ytensor[i]) * torch.log(output)
    print(loss)

tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([4.7684e-07], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([0.0001], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([7.1526e-07], grad_fn=<SubBackward0>)
tensor([1.5497e-06], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([3.5763e-07], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_fn=<SubBackward0>)
tensor([-0.], grad_

In [261]:
W

tensor([[ 5.0363e-05,  8.8873e-05,  3.5210e-05, -1.4706e-05,  8.6917e-05,
         -5.2186e-05,  7.3739e-05,  9.5012e-05, -4.9663e-05, -1.6828e-04,
         -4.3513e-04, -6.4321e-04, -3.7131e-04, -2.9355e-04, -2.2788e-04,
         -3.7441e-04, -4.9457e-04, -6.8395e-04, -4.1283e-04, -4.2822e-05,
         -5.6733e-05,  7.3563e-05,  4.5582e-05, -2.0960e-05, -8.8014e-05,
         -6.8810e-05, -3.4419e-05, -7.6996e-05,  8.9316e-05,  5.9910e-05,
          5.9616e-05,  1.7217e-06,  3.2591e-05,  7.0256e-05, -2.1169e-05,
         -4.1114e-04, -6.9170e-04, -1.0314e-03, -1.2743e-03, -1.0199e-03,
         -1.2177e-03, -1.1182e-03, -1.0621e-03, -1.1234e-03, -1.4125e-03,
         -1.2582e-03, -1.2213e-03, -8.7819e-04, -5.1930e-04, -9.4349e-05,
          2.4515e-06,  4.3263e-05, -5.1975e-06, -7.0043e-05, -9.2222e-05,
         -3.4216e-05,  6.1322e-05, -2.6001e-06,  5.4259e-05,  5.9735e-05,
         -9.5766e-05, -1.0575e-05, -6.0718e-04, -8.1626e-04, -1.0540e-03,
         -1.0286e-03, -1.0921e-03, -1.

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.conv2(nn.Conv2d(6, 16, 5))
        self.fc1 = nn.Linear(120, 84)
        self.fc2 = nn.Linear(84, 10)
    
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv1(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc1(c))
        return x
    
    def num_flat_features(self, x):
        size = x[1:]
        num_features = 1
        for s in size:
            num_features *= s 
        return num_features

In [284]:
import torchvision 
import torchvision.transforms as transforms


In [ ]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

In [ ]:
trainloader = torch.utils.data.DataLoader(trainset, batch_size=32,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)


In [ ]:
import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

for epoch in range(2):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
        if i % 2000 == 1999:    # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training')